### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by JianghaoWu** [TJUQiangChen/FLARE24#1]
Thank you for your excellent work. I was wondering if you could share your Dockerfile?

**Comment by TJUQiangChen** [comment]
> Thank you for your excellent work. I was wondering if you could share your Dockerfile?

Thank you for your interest and kind words! We're currently preparing to release the Dockerfile and it should be available soon.

**Comment by TJUQiangChen** [comment]
> > Thank you for your excellent work. I was wondering if you could share your Dockerfile?
> 
> Thank you for your interest and kind words! We're currently preparing to release the Dockerfile and it should be available soon.


@JianghaoWu We have already updated the Docker related information in our README.md. You can find the Docker usage instructions and image download link in the [Docker section](https://github.com/TJUQiangChen/FLARE24-task3?tab=readme-ov-file#-docker) of our README.

The Docker image is available through BaiduNetDisk with the provided download link and extraction code. This contains everything needed to run the inference.
